# Generated by Django 5.1.3 on 2024-11-25 07:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBookingGadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_gadgets', to='hotel.hotelbooking')),
                ('gadget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.hotelroomgadget')),
            ],
        ),
    ]
