# Generated by Django 5.1.3 on 2024-11-22 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotelroomtype_gadgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='description',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
