# Generated by Django 5.1.3 on 2024-11-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotelroomtype_base_price_hotelroomtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='number_of_guests',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
    ]
